#!/bin/sh
#
# unicorn_job - this script starts and stops the unicorn
#
# chkconfig:   - 85 15
# description: unicorn_job is database based asynchronous priority queue system
# processname: unicorn_job
# pidfile:     /opt/enju_trunk/var/run/nginx.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

ENJUUSER=enju
ENJUHOME=/opt/enju_trunk

start() {
  echo -n $"Starting unicorn:"
  su - $ENJUUSER -c "cd $ENJUHOME ; RAILS_ENV=production bundle exec rake enju_trunk:unicorn:start"
  retval=$?
  echo
  return $retval
}

stop() {
  echo -n $"Stopping unicorn: "
  su - $ENJUUSER -c "cd $ENJUHOME ; RAILS_ENV=production bundle exec rake enju_trunk:unicorn:stop"
  retval=$?
  echo
  return $retval
}

case "$1" in
  start)
    rh_status_q && exit 0
    $1
    ;;
  stop)
    rh_status_q || exit 0
    $1
    ;;

  *)
    echo $"Usage: $0 {start|stop}"
    exit 2
esac
