require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ApprovalExtextsController do

  # This should return the minimal set of attributes required to create a valid
  # ApprovalExtext. As you add validations to ApprovalExtext, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ApprovalExtextsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all approval_extexts as @approval_extexts" do
      approval_extext = ApprovalExtext.create! valid_attributes
      get :index, {}, valid_session
      assigns(:approval_extexts).should eq([approval_extext])
    end
  end

  describe "GET show" do
    it "assigns the requested approval_extext as @approval_extext" do
      approval_extext = ApprovalExtext.create! valid_attributes
      get :show, {:id => approval_extext.to_param}, valid_session
      assigns(:approval_extext).should eq(approval_extext)
    end
  end

  describe "GET new" do
    it "assigns a new approval_extext as @approval_extext" do
      get :new, {}, valid_session
      assigns(:approval_extext).should be_a_new(ApprovalExtext)
    end
  end

  describe "GET edit" do
    it "assigns the requested approval_extext as @approval_extext" do
      approval_extext = ApprovalExtext.create! valid_attributes
      get :edit, {:id => approval_extext.to_param}, valid_session
      assigns(:approval_extext).should eq(approval_extext)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ApprovalExtext" do
        expect {
          post :create, {:approval_extext => valid_attributes}, valid_session
        }.to change(ApprovalExtext, :count).by(1)
      end

      it "assigns a newly created approval_extext as @approval_extext" do
        post :create, {:approval_extext => valid_attributes}, valid_session
        assigns(:approval_extext).should be_a(ApprovalExtext)
        assigns(:approval_extext).should be_persisted
      end

      it "redirects to the created approval_extext" do
        post :create, {:approval_extext => valid_attributes}, valid_session
        response.should redirect_to(ApprovalExtext.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved approval_extext as @approval_extext" do
        # Trigger the behavior that occurs when invalid params are submitted
        ApprovalExtext.any_instance.stub(:save).and_return(false)
        post :create, {:approval_extext => { "name" => "invalid value" }}, valid_session
        assigns(:approval_extext).should be_a_new(ApprovalExtext)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ApprovalExtext.any_instance.stub(:save).and_return(false)
        post :create, {:approval_extext => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested approval_extext" do
        approval_extext = ApprovalExtext.create! valid_attributes
        # Assuming there are no other approval_extexts in the database, this
        # specifies that the ApprovalExtext created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ApprovalExtext.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => approval_extext.to_param, :approval_extext => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested approval_extext as @approval_extext" do
        approval_extext = ApprovalExtext.create! valid_attributes
        put :update, {:id => approval_extext.to_param, :approval_extext => valid_attributes}, valid_session
        assigns(:approval_extext).should eq(approval_extext)
      end

      it "redirects to the approval_extext" do
        approval_extext = ApprovalExtext.create! valid_attributes
        put :update, {:id => approval_extext.to_param, :approval_extext => valid_attributes}, valid_session
        response.should redirect_to(approval_extext)
      end
    end

    describe "with invalid params" do
      it "assigns the approval_extext as @approval_extext" do
        approval_extext = ApprovalExtext.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ApprovalExtext.any_instance.stub(:save).and_return(false)
        put :update, {:id => approval_extext.to_param, :approval_extext => { "name" => "invalid value" }}, valid_session
        assigns(:approval_extext).should eq(approval_extext)
      end

      it "re-renders the 'edit' template" do
        approval_extext = ApprovalExtext.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ApprovalExtext.any_instance.stub(:save).and_return(false)
        put :update, {:id => approval_extext.to_param, :approval_extext => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested approval_extext" do
      approval_extext = ApprovalExtext.create! valid_attributes
      expect {
        delete :destroy, {:id => approval_extext.to_param}, valid_session
      }.to change(ApprovalExtext, :count).by(-1)
    end

    it "redirects to the approval_extexts list" do
      approval_extext = ApprovalExtext.create! valid_attributes
      delete :destroy, {:id => approval_extext.to_param}, valid_session
      response.should redirect_to(approval_extexts_url)
    end
  end

end
