require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClaimTypesController do

  # This should return the minimal set of attributes required to create a valid
  # ClaimType. As you add validations to ClaimType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClaimTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all claim_types as @claim_types" do
      claim_type = ClaimType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:claim_types).should eq([claim_type])
    end
  end

  describe "GET show" do
    it "assigns the requested claim_type as @claim_type" do
      claim_type = ClaimType.create! valid_attributes
      get :show, {:id => claim_type.to_param}, valid_session
      assigns(:claim_type).should eq(claim_type)
    end
  end

  describe "GET new" do
    it "assigns a new claim_type as @claim_type" do
      get :new, {}, valid_session
      assigns(:claim_type).should be_a_new(ClaimType)
    end
  end

  describe "GET edit" do
    it "assigns the requested claim_type as @claim_type" do
      claim_type = ClaimType.create! valid_attributes
      get :edit, {:id => claim_type.to_param}, valid_session
      assigns(:claim_type).should eq(claim_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ClaimType" do
        expect {
          post :create, {:claim_type => valid_attributes}, valid_session
        }.to change(ClaimType, :count).by(1)
      end

      it "assigns a newly created claim_type as @claim_type" do
        post :create, {:claim_type => valid_attributes}, valid_session
        assigns(:claim_type).should be_a(ClaimType)
        assigns(:claim_type).should be_persisted
      end

      it "redirects to the created claim_type" do
        post :create, {:claim_type => valid_attributes}, valid_session
        response.should redirect_to(ClaimType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved claim_type as @claim_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClaimType.any_instance.stub(:save).and_return(false)
        post :create, {:claim_type => { "name" => "invalid value" }}, valid_session
        assigns(:claim_type).should be_a_new(ClaimType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClaimType.any_instance.stub(:save).and_return(false)
        post :create, {:claim_type => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested claim_type" do
        claim_type = ClaimType.create! valid_attributes
        # Assuming there are no other claim_types in the database, this
        # specifies that the ClaimType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ClaimType.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => claim_type.to_param, :claim_type => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested claim_type as @claim_type" do
        claim_type = ClaimType.create! valid_attributes
        put :update, {:id => claim_type.to_param, :claim_type => valid_attributes}, valid_session
        assigns(:claim_type).should eq(claim_type)
      end

      it "redirects to the claim_type" do
        claim_type = ClaimType.create! valid_attributes
        put :update, {:id => claim_type.to_param, :claim_type => valid_attributes}, valid_session
        response.should redirect_to(claim_type)
      end
    end

    describe "with invalid params" do
      it "assigns the claim_type as @claim_type" do
        claim_type = ClaimType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClaimType.any_instance.stub(:save).and_return(false)
        put :update, {:id => claim_type.to_param, :claim_type => { "name" => "invalid value" }}, valid_session
        assigns(:claim_type).should eq(claim_type)
      end

      it "re-renders the 'edit' template" do
        claim_type = ClaimType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClaimType.any_instance.stub(:save).and_return(false)
        put :update, {:id => claim_type.to_param, :claim_type => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested claim_type" do
      claim_type = ClaimType.create! valid_attributes
      expect {
        delete :destroy, {:id => claim_type.to_param}, valid_session
      }.to change(ClaimType, :count).by(-1)
    end

    it "redirects to the claim_types list" do
      claim_type = ClaimType.create! valid_attributes
      delete :destroy, {:id => claim_type.to_param}, valid_session
      response.should redirect_to(claim_types_url)
    end
  end

end
