require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe KeycodesController do

  # This should return the minimal set of attributes required to create a valid
  # Keycode. As you add validations to Keycode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KeycodesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all keycodes as @keycodes" do
      keycode = Keycode.create! valid_attributes
      get :index, {}, valid_session
      assigns(:keycodes).should eq([keycode])
    end
  end

  describe "GET show" do
    it "assigns the requested keycode as @keycode" do
      keycode = Keycode.create! valid_attributes
      get :show, {:id => keycode.to_param}, valid_session
      assigns(:keycode).should eq(keycode)
    end
  end

  describe "GET new" do
    it "assigns a new keycode as @keycode" do
      get :new, {}, valid_session
      assigns(:keycode).should be_a_new(Keycode)
    end
  end

  describe "GET edit" do
    it "assigns the requested keycode as @keycode" do
      keycode = Keycode.create! valid_attributes
      get :edit, {:id => keycode.to_param}, valid_session
      assigns(:keycode).should eq(keycode)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Keycode" do
        expect {
          post :create, {:keycode => valid_attributes}, valid_session
        }.to change(Keycode, :count).by(1)
      end

      it "assigns a newly created keycode as @keycode" do
        post :create, {:keycode => valid_attributes}, valid_session
        assigns(:keycode).should be_a(Keycode)
        assigns(:keycode).should be_persisted
      end

      it "redirects to the created keycode" do
        post :create, {:keycode => valid_attributes}, valid_session
        response.should redirect_to(Keycode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved keycode as @keycode" do
        # Trigger the behavior that occurs when invalid params are submitted
        Keycode.any_instance.stub(:save).and_return(false)
        post :create, {:keycode => { "name" => "invalid value" }}, valid_session
        assigns(:keycode).should be_a_new(Keycode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Keycode.any_instance.stub(:save).and_return(false)
        post :create, {:keycode => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested keycode" do
        keycode = Keycode.create! valid_attributes
        # Assuming there are no other keycodes in the database, this
        # specifies that the Keycode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Keycode.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => keycode.to_param, :keycode => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested keycode as @keycode" do
        keycode = Keycode.create! valid_attributes
        put :update, {:id => keycode.to_param, :keycode => valid_attributes}, valid_session
        assigns(:keycode).should eq(keycode)
      end

      it "redirects to the keycode" do
        keycode = Keycode.create! valid_attributes
        put :update, {:id => keycode.to_param, :keycode => valid_attributes}, valid_session
        response.should redirect_to(keycode)
      end
    end

    describe "with invalid params" do
      it "assigns the keycode as @keycode" do
        keycode = Keycode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Keycode.any_instance.stub(:save).and_return(false)
        put :update, {:id => keycode.to_param, :keycode => { "name" => "invalid value" }}, valid_session
        assigns(:keycode).should eq(keycode)
      end

      it "re-renders the 'edit' template" do
        keycode = Keycode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Keycode.any_instance.stub(:save).and_return(false)
        put :update, {:id => keycode.to_param, :keycode => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested keycode" do
      keycode = Keycode.create! valid_attributes
      expect {
        delete :destroy, {:id => keycode.to_param}, valid_session
      }.to change(Keycode, :count).by(-1)
    end

    it "redirects to the keycodes list" do
      keycode = Keycode.create! valid_attributes
      delete :destroy, {:id => keycode.to_param}, valid_session
      response.should redirect_to(keycodes_url)
    end
  end

end
